// <auto-generated />
namespace Lisa.Zuma.BlueJay.Web.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class DossierDetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DossierDetails));
        
        string IMigrationMetadata.Id
        {
            get { return "201403101116175_DossierDetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
